// flow-typed signature: c44d1f39f90e42a38b5511afc2859cf2
// flow-typed version: <<STUB>>/eslint-plugin-async-await_v^0.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-async-await'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-async-await' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-async-await/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-async-await/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-async-await/lib/index'>;
}
